### ISSUE TITLE
Duplicated short opt in ArchiveCommand.php

### ISSUE THREAD

**Issue by mbattista** [c9s/CLIFramework#104]
'composer' and 'compress?' option both have the short opt -c. This leads to following error if you run cli.php:
<pre>
>php71 cli help
Option conflict: -c is already defined.
</pre><br>
Snipplett of the error in Question.
<pre>
        $opts->add('c|composer:', 'The composer.json file. If --working-dir is ignored, dirname of the composer.json will be used.')
            ->isa('file')
            ->defaultValue('composer.json')
            ;

        $opts->add('c|compress?', 'compress type: gz, bz2')
            ->defaultValue('gz')
            ->validValues(array('gz', 'bz2'))
            ;
</pre>

**Comment by DanielRuf** [comment]
Should be fixed by https://github.com/c9s/CLIFramework/pull/105

**Comment by pruderman-champlain** [comment]
Thank you.  Any plans to release this to packagist?  It is broken there now.

**Comment by DanielRuf** [comment]
https://github.com/c9s/CLIFramework/releases

**Comment by pruderman-champlain** [comment]
Right the fix isn't in any of the releases.  The current release doesn't work.  I'll take that as a 'no'.

**Comment by c9s** [comment]
Solved and released
