### ISSUE TITLE
Add BashCompletionCommand

### ISSUE THREAD

**Issue by marcioAlmada** [c9s/CLIFramework#26]
Zsh auto bash completion is great, let's add a bash completion too.

**Comment by c9s** [comment]
https://github.com/c9s/CLIFramework/tree/bash-completion Working in progress

**Comment by c9s** [comment]
I wrote a bash completion script that might be suitable to apply the metadata from commands.

**Comment by c9s** [comment]
@marcioAlmada I just finished the bash completion! 

https://github.com/c9s/CLIFramework/compare/2.3.0...master

**Comment by c9s** [comment]
[Imgur](http://i.imgur.com/sF5UPX5.gifv)

**Comment by marcioAlmada** [comment]
This has been on my endless to do list like forever and you did it. Thank you!
