### ISSUE TITLE
Built-in Daemon option support

### ISSUE THREAD

**Issue by c9s** [c9s/CLIFramework#33]
When using `--daemon`, we fork the current process in the background and create a pidfile.

**Comment by shinnya** [comment]
I will work on this issue next.
To support `--daemon` option, I'm going to add `daemonize` method to `Utils` class by `pcntl_fork`. The way of daemonizing a process will be like https://github.com/memcached/memcached/blob/c5530027c8ea28674358327ab8212ebaf014c848/daemon.c .
And if `pcntl_fork` isn't supported by the PHP, it might be reasonable that giving `--daemon` option causes warnings.

**Comment by c9s** [comment]
great! thanks!  memcached is a good reference.

I think the daemonize can be added to `CommandBase` class directly or via a simple extension, so that we can daemonize an app or a subcommand. further, we can create the pid file in a specific directory (from cliframework config file or the command line option)

**Comment by c9s** [comment]
I think we might need an extension API for something like `Daemonize`, which will provides some options and built-in logics to be integrated into a command class (or app class).

for now, what I can imagine is:

```php
class ServerCommand extends Command {
     public function init() {
          // Inject options, and run logics.
          $this->enableExtension(new Daemonize([ ... options ]));
     }
}
```

We might also need some refactoring for the extension API:

- the run method should trigger events like `run.after` or `run.before`, to call Daemonize::run() method, so that we can register initialization code and finalization code from the extension.
- the caller of `options($opts)` should trigger `options.before` event and `options.after` event around the `options($opts)` method.

**Comment by c9s** [comment]
P.S. Since we want to run php process in background, we might also want to log the messages in a separated file. noted in #40

**Comment by shinnya** [comment]
Okay, I've roughly got what you imagined. I also think that easily injecting the feature of `deamonize` to Command is reasonable.
Then, the extension and event system are nice and I feel that what you means looks like the hook system implemented in Plagger(https://github.com/miyagawa/plagger/blob/master/lib/Plagger/Plugin.pm#L186).

**Comment by c9s** [comment]
yes, something like that. or Class::Trigger written in PHP

**Comment by shinnya** [comment]
Alright.

**Comment by c9s** [comment]
Done! Thanks!
