### ISSUE TITLE
Getting started tutorial doesn't work

### ISSUE THREAD

**Issue by Zyles** [c9s/CLIFramework#81]
Here: https://github.com/c9s/CLIFramework/wiki/Getting-Started

Gives:
```
PHP Fatal error:  Class 'YourApp\Application' not found in /home/yourapp/bin/yourapp on line 4
```
Got a working tutorial?

**Comment by c9s** [comment]
Thanks! it shiuld be fixed now

https://github.com/c9s/CLIFramework/wiki/Getting-Started/_compare/d7ee20e6fb4fc60dbdc43a2f3507744485df342e...5cba8479f03b099cc052da0c9e2f44523824d4ba

**Comment by c9s** [comment]
Work for you?   If not, please re-open this issue. Thanks!
