### ISSUE TITLE
Getting started wiki page

### ISSUE THREAD

**Issue by ValeriyLiquid** [c9s/CLIFramework#86]
Hi, 
I tried to use ``Automatic Zsh Completion Generator``, but had a problem with ``Console`` class, which must initialize parent commands (such as ``zsh``, ``bash`` etc.), which described in ``\CLIFramework\Application``. That's why, I edited your wiki page: https://github.com/c9s/CLIFramework/wiki/Getting-Started to add parent method call.
Is this behavior right?
Thank you :)

**Comment by c9s** [comment]
Yes, you're right. there was a missing `parent::init`

**Comment by c9s** [comment]
@ValeriyLiquid Thanks! I am closing this issue, if you have any issue or need support just fire me another one. ;)
