### ISSUE TITLE
Better commnand line parser

### ISSUE THREAD

**Issue by psincraian** [c9s/CLIFramework#92]
Hi,

I am developing a project with this nice tool but when I run some tests  I found an annoying issue. When I execute the following code:
```
public function test()
{
    // ...
    $this->runCommand("program arg1 \"arg2.1 arg2.2\" arg3");
    // ...
}
```
The arguments passed to program are
```
array() = 
{
    [0] = "program",
    [1] = "arg1",
    [2] = "\"arg2.1",
    [3] = "arg2.2\"",
    [4] = "arg3"
}
```
And I expect something like that:
```
array() = 
{
    [0] = "program",
    [1] = "arg1",
    [2] = "arg2.1 arg2.2",
    [3] = "arg3"
}
```

It is a bit annoying and I have created a better parser. How can I post my contribution in this project? 

Thanks,
Petru Rares.

**Comment by c9s** [comment]
The runCommand method defined in test suite is quiet lacking in parsing arguments. (It didn't use the command parser)

However you can simply pass array instead of command string to test your app

```php
$this->runCommand(["program", "arg1", "arg2.1 arg2.2", "arg3"]);
```

**Comment by c9s** [comment]
Here is the implementation of `runCommand` method:

```php
    public function runCommand($args) {
        if (is_string($args)) {
            $args = preg_split('/\s+/',$args);
        }
        return $this->app->run($args);
    }
```

**Comment by psincraian** [comment]
I saw it. I have made a simple improvement to the class. Now works more like command line does. Here is the patch: [patch.zip](https://github.com/c9s/CLIFramework/files/179663/patch.zip)

Simply I have added a new class that parses a string and return the arguments. Also I have added some tests to show that it works correctly :) 

I know it isn't a big improvement, but if you like it you can add it to the project.

**Comment by c9s** [comment]
Hi! Thanks for your work. It would be great if you can send me a pull request instad of zip file. :) Then I can merge it as soon as possible.
